library(dplyr)
library(tidyverse)
vine_df <- read.csv(file='vine1.csv', check.names = F)
fivestar <-subset(vine_df, star_rating == "5")
vineyes <- subset(fivestar, vine == "Y")
vineno <- subset(fivestar, vine == "N")
#vine_df$total_votes <- factor(vine_df$total_votes) 
t.test(fivestar$total_votes)
summary(t.test(fivestar$total_votes))
t.test(fivestar$total_votes, vineyes$total_votes)
summary(t.test(fivestar$total_votes, vineyes$total_votes))
t.test(fivestar$total_votes, vineyes$total_votes, alternative="g")
t.test(fivestar$total_votes, vineyes$total_votes, alternative='l')
